-- In-house articles: short, AI-written roundups that summarize recent India/NRI headlines FOR the
-- community, keeping readers on-site (vs. linking straight out). Each article is grounded in — and cites
-- — the real headlines it was built from (stored in `sources`), and is clearly labelled as an AI summary
-- so we never present invented facts as reporting. Generated by ArticlesAgent when the LLM is active.
CREATE TABLE IF NOT EXISTS articles (
    id           BIGSERIAL PRIMARY KEY,
    slug         TEXT NOT NULL UNIQUE,
    title        TEXT NOT NULL,
    dek          TEXT,                              -- one-line standfirst/summary
    body         TEXT NOT NULL,                     -- plain text / light markdown, paragraphs on blank lines
    category     TEXT NOT NULL DEFAULT 'general',
    sources      JSONB NOT NULL DEFAULT '[]',       -- [{title,url,source}] the roundup cites
    status       TEXT NOT NULL DEFAULT 'published', -- published | hidden
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_articles_published ON articles (created_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles (category, created_at DESC);
